pr: none
pool:
  vmImage: 'ubuntu-latest'

variables:
  # Terraform settings
  terraformWorkingDirectory: '/opt/hostedtoolcache/terraform/1.5.6/x64/terraform'

stages:
- stage: Deployment
  jobs:
  - job: deploy_on_test
    continueOnError: false
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'terraform'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: TerraformInstaller@0
      displayName: "install"
      inputs:
        terraformVersion: '1.5.6'

    - task: AzureKeyVault@2
      displayName: 'Download Azure KV'
      inputs:
        azureSubscription: 'sc-arm-nhatthai'
        KeyVaultName: 'az-kv-terraform-test'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
        provider: azurerm
        command: init
        backendServiceArm: sc-arm-nhatthai
        backendAzureRmResourceGroupName: 'containers'
        backendAzureRmStorageAccountName: 'azterraformstateex'
        backendAzureRmContainerName: 'terraform-container-test'
        backendAzureRmKey: 'test.auth0.tfstate'

    - task: TerraformTaskV3@3
      displayName: 'validate'
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
        provider: 'azurerm'
        command: 'validate'


    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
        provider: 'azurerm'
        environmentServiceNameAzureRM: sc-arm-nhatthai
        command: 'plan'
        commandOptions: >-
          -var-file="Environments/test.tfvars" -lock=false \
          -var "auth0_client_id=$(TFAuth0ClientId)" \
          -var "auth0_client_secret=$(TFAuth0ClientSecret)"

    - task: TerraformTaskV3@3
      displayName: 'Terraform Apply'
      inputs:
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: sc-arm-nhatthai
        commandOptions: >-
          -var-file="terraform/Environments/test.tfvars" -lock=false \
          -var "auth0_client_id=$(TFAuth0ClientId)" \
          -var "auth0_client_secret=$(TFAuth0ClientSecret)" -auto-approve
