pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: TerraformCICD # The name used to reference this repository in the checkout step
    type: github
    name: nhatthaiquang-agilityio/Terraform-CI-CD
    endpoint: nhatthaiquang-agilityio
    ref: refs/heads/main

variables:
  TerraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  AzureKeyVaultServiceConnectionName: AzureResourceConnection
  StorgeAccountsName: terraformstateexample
  AzureResourceGroupName: containers
  AzureContainerName: terraform-container-state

stages:
- stage: DeployInTest
  displayName: Deployment in Test
  jobs:
    - template: jobs/create-app-auth0.yml@TerraformCICD
      parameters:
        EnvironmentName: Test
        AzureKeyVaultServiceConnectionName: ${{ variables.AzureKeyVaultServiceConnectionName }}
        AzureResourceGroupName: ${{ variables.AzureResourceGroupName }}
        AzureContainerName: ${{ variables.AzureContainerName }}
        AzureRmKeyTFState: test.auth0.tfstate
        KeyVaultName: AzKvTerraformVariables
        StorgeAccountsName: ${{ variables.StorgeAccountsName }}
        TerraformWorkingDirectory: ${{ variables.TerraformWorkingDirectory }}
        VarFilePath: 'Environments/test.tfvars'

- stage: DeployInStage
  displayName: Deployment in Stage
  jobs:
    - template: jobs/create-app-auth0.yml@TerraformCICD
      parameters:
        EnvironmentName: Stage
        AzureKeyVaultServiceConnectionName: ${{ variables.AzureKeyVaultServiceConnectionName }}
        AzureResourceGroupName: ${{ variables.AzureResourceGroupName }}
        AzureRmKeyTFState: stage.auth0.tfstate
        AzureContainerName: ${{ variables.AzureContainerName }}
        KeyVaultName: AzKvTerraformVariables
        StorgeAccountsName: ${{ variables.StorgeAccountsName }}
        TerraformWorkingDirectory: ${{ variables.TerraformWorkingDirectory }}
        VarFilePath: 'Environments/stage.tfvars'
